/*
 * Direitos reservados a Ramon Lacava Gutierrez Gonçales
 * ramonrune@gmail.com
 */
package com.healthsystem.user;

import com.healthsystem.util.EmailManager;
import com.healthsystem.healthinstitution.*;
import com.healthsystem.util.dataprovider.CountryList;
import com.healthsystem.util.dataprovider.CountryModel;
import com.healthsystem.util.Criptography;
import com.healthsystem.util.DocumentValidator;
import com.healthsystem.util.ResizeUtil;
import com.healthsystem.util.ViewConfigurable;
import com.healthsystem.util.azure.AzureBlob;
import com.healthsystem.util.azure.ImageFilter;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;

/**
 * @author Ramon Lacava Gutierrez Gonçales
 * @version 1.0.0
 * @date 30/06/2018 19:33:20
 */
public class UserAddAdminHealthInstitutionSystemAccountWindow extends JDialog implements ViewConfigurable {

    private java.util.ResourceBundle i18n = java.util.ResourceBundle.getBundle("com/healthsystem/user/Bundle"); // NOI18N

    private JFileChooser fc;

    private UserPanel userPanel;

    /**
     * Cria um novo formulário HealthInstitutionAddWindow
     */
    public UserAddAdminHealthInstitutionSystemAccountWindow() {

        setResizable(false);

        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        loginTextField = new javax.swing.JTextField();
        passwordPasswordTextField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        addAccountButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/healthsystem/user/Bundle"); // NOI18N
        setTitle(bundle.getString("UserAddAdminHealthInstitutionSystemAccountWindow.title_1")); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText(bundle.getString("UserAddAdminHealthInstitutionSystemAccountWindow.jLabel1.text_1")); // NOI18N

        loginTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        passwordPasswordTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        passwordPasswordTextField.setText(bundle.getString("UserAddAdminHealthInstitutionSystemAccountWindow.passwordPasswordTextField.text_1")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText(bundle.getString("UserAddAdminHealthInstitutionSystemAccountWindow.jLabel2.text_1")); // NOI18N

        addAccountButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addAccountButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/success.png"))); // NOI18N
        addAccountButton.setText(bundle.getString("UserAddAdminHealthInstitutionSystemAccountWindow.addAccountButton.text_1")); // NOI18N
        addAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAccountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addAccountButton)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(loginTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                        .addComponent(passwordPasswordTextField)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(addAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAccountButtonActionPerformed

        boolean success = true;

        if (success) {
            String login = loginTextField.getText();

            if (login.length() > 100) {
                JOptionPane.showMessageDialog(null, i18n.getString("UserAddWindow.validate.login"));
                success = false;
            }
        }

        if (success) {
            String login = loginTextField.getText();

            if (login.trim().equals("")) {
                JOptionPane.showMessageDialog(null, i18n.getString("UserAddWindow.validate.login.notnull"));
                success = false;
            }
        }

        if (success) {
            String login = loginTextField.getText();

            if (!EmailManager.isValidEmailAddress(login)) {
                JOptionPane.showMessageDialog(null, i18n.getString("UserAddWindow.validate.login.invalid"));
                success = false;
            }
        }

        if (success) {
            String password = passwordPasswordTextField.getText();

            if (password.trim().equals("")) {
                JOptionPane.showMessageDialog(null, i18n.getString("UserAddWindow.validate.password.notnull"));
                success = false;
            }
        }

        if (success) {
            HealthInstitutionModel healthInstitution = healthInstitutionDAO.getHealthInstitution(HealthInstitutionSingleton.getInstance().getIdHealthInstitution());

            System.out.println("healthinstituton " + healthInstitution.getCountry());
            StringBuilder id = new StringBuilder();

            Date date = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String bornDate = sdf.format(date);

            boolean ok = userDAO.add(
                    loginTextField.getText(),
                    UUID.randomUUID().toString(),
                    healthInstitution.getCountryCode(),
                    healthInstitution.getPostalCode(),
                    healthInstitution.getState(),
                    healthInstitution.getCity(),
                    healthInstitution.getNeighborhood(),
                    healthInstitution.getStreet(),
                    healthInstitution.getNumber(),
                    "USER_DEFAULT_PHOTO.jpg",
                    healthInstitution.getTelephone(),
                    loginTextField.getText(),
                    Criptography.sha256(passwordPasswordTextField.getText()),
                    "1",
                    "3",
                    bornDate,
                    id);

            if (ok) {
                ok = healthInstitutionDAO.addBind(HealthInstitutionSingleton.getInstance().getIdHealthInstitution(), id.toString(), "1");

            }

            if (ok) {
                if (userPanel != null) {
                    userPanel.populateData();
                }
                setVisible(false);
                JOptionPane.showMessageDialog(null, i18n.getString("UserAddWindow.success"));

                dispose();
            }

        }


    }//GEN-LAST:event_addAccountButtonActionPerformed

    private HealthInstitutionDAO healthInstitutionDAO = new HealthInstitutionDAO();
    private UserDAO userDAO = new UserDAO();

    public void setUserPanel(UserPanel userPanel) {
        this.userPanel = userPanel;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAddAdminHealthInstitutionSystemAccountWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAddAdminHealthInstitutionSystemAccountWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAddAdminHealthInstitutionSystemAccountWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAddAdminHealthInstitutionSystemAccountWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserAddAdminHealthInstitutionSystemAccountWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAccountButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JPasswordField passwordPasswordTextField;
    // End of variables declaration//GEN-END:variables

}
