/*
 * Direitos reservados a Ramon Lacava Gutierrez Gonçales
 * ramonrune@gmail.com
 */
package com.healthsystem;

import com.healthsystem.user.UserDAO;
import com.healthsystem.home.HomeScreen;
import com.healthsystem.user.UserSingleton;
import com.healthsystem.util.ViewConfigurable;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.Toolkit;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Locale;
import java.util.PropertyResourceBundle;
import java.util.ResourceBundle;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.EmptyBorder;

/**
 * @author Ramon Lacava Gutierrez Gonçales
 * @version 1.0.0
 * @date 23/06/2018 21:13:28
 */
public class LoginScreen extends javax.swing.JFrame implements ViewConfigurable {

    private UserDAO userDAO = new UserDAO();
    private java.util.ResourceBundle i18n = java.util.ResourceBundle.getBundle("com/healthsystem/Bundle"); // NOI18N

    /**
     * Cria um novo formulário SplashScreen
     */
    public LoginScreen() {
        defineScreen(this);
        setResizable(false);
        initComponents();

        centerScreen(this);
        
        //passwordPasswordField.setText("1234");
        //loginTextField.setText("ramonrune@gmail.com");
        
       loginTextField.setText("drauzeo@gmail.com");
       passwordPasswordField.setText("123456");
        //loginTextField.setText("ramonrune114@gmail.com");
        // loginTF.setText("medicoo@gmail.com");
        //passwordPasswordField.setText("1111");
        loadingIcon.setVisible(false);
        jPanel1.revalidate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginTextField = new javax.swing.JTextField();
        passwordPasswordField = new javax.swing.JPasswordField();
        userLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        appIcon = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        passwordIcon = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        loadingIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/healthsystem/Bundle"); // NOI18N
        setTitle(bundle.getString("LoginScreen.title")); // NOI18N
        setPreferredSize(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        loginTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(loginTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 264, 30));

        passwordPasswordField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        passwordPasswordField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(passwordPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 264, 30));

        userLabel.setBackground(new java.awt.Color(255, 255, 255));
        userLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        userLabel.setText(bundle.getString("LoginScreen.userLabel.text")); // NOI18N
        jPanel1.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        passwordLabel.setBackground(new java.awt.Color(255, 255, 255));
        passwordLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        passwordLabel.setText(bundle.getString("LoginScreen.passwordLabel.text")); // NOI18N
        jPanel1.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        appIcon.setBackground(new java.awt.Color(255, 255, 255));
        appIcon.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        appIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_100x100.png"))); // NOI18N
        jPanel1.add(appIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 100, 140));

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        jPanel1.add(userIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        passwordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/password.png"))); // NOI18N
        jPanel1.add(passwordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        loginButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        loginButton.setText(bundle.getString("LoginScreen.loginButton.text")); // NOI18N
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 260, 40));

        loadingIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loading_1.gif"))); // NOI18N
        loadingIcon.setText(bundle.getString("LoginScreen.loadingIcon.text")); // NOI18N
        jPanel1.add(loadingIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 350, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        changeVisibility(false);

        ExecutorService executor = Executors.newSingleThreadExecutor();
        executor.execute(() -> {

            boolean userExist = userDAO.userExist(loginTextField.getText(), passwordPasswordField.getText());

            if (userExist) {

                if (UserSingleton.getInstance().isPatient()) {
                    JOptionPane.showMessageDialog(null, i18n.getString("LoginScreen.accessDenied"));
                    dispose();
                } else {
                    HomeScreen home = new HomeScreen();
                    home.setVisible(true);

                    dispose();
                }

            } else {
                changeVisibility(true);
                JOptionPane.showMessageDialog(null, i18n.getString("LoginScreen.notFound"));
            }

        });

        executor.shutdown();

    }//GEN-LAST:event_loginButtonActionPerformed
    private void changeVisibility(boolean status) {

        loginButton.setVisible(status);
        loginTextField.setVisible(status);
        passwordIcon.setVisible(status);
        userLabel.setVisible(status);
        userIcon.setVisible(status);
        passwordLabel.setVisible(status);
        passwordPasswordField.setVisible(status);
        passwordIcon.setVisible(status);
        appIcon.setVisible(status);
        loadingIcon.setVisible(!status);
        jPanel1.revalidate();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /*try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
         */
 /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appIcon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loadingIcon;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JLabel passwordIcon;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordPasswordField;
    private javax.swing.JLabel userIcon;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables

}
