/*
 * Direitos reservados a Ramon Lacava Gutierrez Gonçales
 * ramonrune@gmail.com
 */
package com.healthsystem.patient;

import com.healthsystem.physician.NFCReaderNewSensor;
import com.healthsystem.util.ViewConfigurable;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Usuario
 */
public class AddPatientTagWindow extends javax.swing.JDialog implements ViewConfigurable{
    protected static boolean cont = true;
    protected static String idPatient;
    /**
     * Creates new form AddPatientTagWindow
     */
    public AddPatientTagWindow() {
        setResizable(false);

        initComponents();
        
        setLocationRelativeTo(null);
        
        NFCReaderAddTag.AddPatientTagWindow = AddPatientTagWindow.this;

        if (!NFCReaderAddTag.setupOk()) {
            ExecutorService executor = Executors.newSingleThreadExecutor();
            executor.execute(() -> {

                while (cont) {

                    ExecutorService executor11 = Executors.newSingleThreadExecutor();
                    executor11.execute(() -> {
                        if (NFCReaderAddTag.setupOk()) {

                            statusOk();
                            executor11.shutdown();

                        } else {
                            statusNotOk();

                        }
                    });

                    try {

                        TimeUnit.MILLISECONDS.sleep(1000);

                    } catch (InterruptedException ex) {
                        Logger.getLogger(AddPatientTagWindow.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }

            });
        } else {
            statusOk();
        }
        
         addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                System.out.println("fechando");
                NFCReaderAddTag.close();
            }
        });
    }
    private PatientPanel patientPanel;
    
    public void setPatientPanel(PatientPanel patientPanel){
        this.patientPanel = patientPanel;
    }
    
    
    public static void setPatientId(String idPatient){
        AddPatientTagWindow.idPatient = "";
        AddPatientTagWindow.idPatient = idPatient;
    }
    
    public void charge(){
        patientPanel.chargeTags();
    }
    
    private java.util.ResourceBundle i18n = java.util.ResourceBundle.getBundle("com/healthsystem/physician/Bundle"); // NOI18N

    private void statusOk() {
        errorImageLabel.setVisible(false);
        imageLabel.setVisible(true);

        messageLabel.setText(i18n.getString("NFCReaderPanel.message.insert"));
        messageLabel.updateUI();
        imageLabel.updateUI();
        errorImageLabel.updateUI();
    }

    private void statusNotOk() {
        errorImageLabel.setVisible(true);
        errorImageLabel.updateUI();
        imageLabel.setVisible(false);
        imageLabel.updateUI();
        messageLabel.setText(i18n.getString("NFCReaderPanel.messageLabel.text"));
        messageLabel.updateUI();

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        messageLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        errorImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/healthsystem/patient/Bundle"); // NOI18N
        setTitle(bundle.getString("AddPatientTagWindow.title")); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 350));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 350));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 350));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        messageLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("com/healthsystem/physician/Bundle"); // NOI18N
        messageLabel.setText(bundle1.getString("NFCReaderPanel.messageLabel.text")); // NOI18N
        jPanel1.add(messageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 470, 40));

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nfc_loading.gif"))); // NOI18N
        imageLabel.setText(bundle1.getString("NFCReaderPanel.imageLabel.text")); // NOI18N
        jPanel1.add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, -40, 262, 367));

        errorImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usb_help.gif"))); // NOI18N
        errorImageLabel.setText(bundle1.getString("NFCReaderPanel.errorImageLabel.text")); // NOI18N
        jPanel1.add(errorImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 517, 367));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorImageLabel;
    public static javax.swing.JLabel imageLabel;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel messageLabel;
    // End of variables declaration//GEN-END:variables
}
