/*
 * Direitos reservados a Ramon Lacava Gutierrez Gonçales
 * ramonrune@gmail.com
 */
package com.healthsystem.patient;

import com.healthsystem.util.ViewConfigurable;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class UpdatePatientTagWindow extends javax.swing.JDialog implements ViewConfigurable {

    private java.util.ResourceBundle i18nPatient = java.util.ResourceBundle.getBundle("com/healthsystem/patient/Bundle"); // NOI18N

    public UpdatePatientTagWindow() {
        setResizable(false);

        initComponents();

        setLocationRelativeTo(null);

        List<String> tagTypes = new ArrayList<>();
        tagTypes.add(i18nPatient.getString("UpdatePatientTagWindow.typeofequipament.0"));
        tagTypes.add(i18nPatient.getString("UpdatePatientTagWindow.typeofequipament.1"));
        tagTypes.add(i18nPatient.getString("UpdatePatientTagWindow.typeofequipament.2"));
        tagTypes.add(i18nPatient.getString("UpdatePatientTagWindow.typeofequipament.3"));
        tagTypes.add(i18nPatient.getString("UpdatePatientTagWindow.typeofequipament.4"));

        tagTypeComboBox.setModel(new DefaultComboBoxModel(tagTypes.toArray()));

    }
    
    private PatientPanel patientPanel;

    public PatientPanel getPatientPanel() {
        return patientPanel;
    }

    public void setPatientPanel(PatientPanel patientPanel) {
        this.patientPanel = patientPanel;
    }
    
    

    private PatientTagModel tagModel;

    public PatientTagModel getTagModel() {
        return tagModel;
    }

    public void setTagModel(PatientTagModel tagModel) {
        this.tagModel = tagModel;
        Pattern p = Pattern.compile("-?\\d+");
        tagTypeComboBox.setSelectedIndex(Integer.parseInt(tagModel.getTagType()));

        tagNameTextField.setText(tagModel.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tagNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tagTypeComboBox = new javax.swing.JComboBox<>();
        updatePatientTagButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/healthsystem/patient/Bundle"); // NOI18N
        setTitle(bundle.getString("UpdatePatientTagWindow.title")); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText(bundle.getString("UpdatePatientTagWindow.jLabel1.text")); // NOI18N

        tagNameTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText(bundle.getString("UpdatePatientTagWindow.jLabel2.text")); // NOI18N

        tagTypeComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        updatePatientTagButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        updatePatientTagButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/success.png"))); // NOI18N
        updatePatientTagButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePatientTagButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(updatePatientTagButton)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tagNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tagTypeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 329, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tagNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tagTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(updatePatientTagButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatePatientTagButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePatientTagButtonActionPerformed

        boolean ok = patientDAO.updateTag(tagModel.getIdPatientTag(), tagNameTextField.getText(), String.valueOf(tagTypeComboBox.getSelectedIndex()));
        
        if(ok){
            setVisible(false);
            patientPanel.chargeTags();
            JOptionPane.showMessageDialog(null, i18nPatient.getString("UpdatePatientTagWindow.success"));
            dispose();
        }
       
        
        
    }//GEN-LAST:event_updatePatientTagButtonActionPerformed
    private PatientDAO patientDAO = new PatientDAO();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tagNameTextField;
    private javax.swing.JComboBox<String> tagTypeComboBox;
    private javax.swing.JButton updatePatientTagButton;
    // End of variables declaration//GEN-END:variables
}
