/*
 * Direitos reservados a Ramon Lacava Gutierrez Gonçales
 * ramonrune@gmail.com
 */
package com.healthsystem.physician;

import com.healthsystem.patient.PatientDAO;
import com.healthsystem.patient.PatientModel;
import com.healthsystem.patient.PatientPanel;
import static com.healthsystem.physician.NFCReader.nfcReaderPanel;
import com.healthsystem.user.UserDAO;
import com.healthsystem.util.ViewConfigurable;
import com.healthsystem.util.WindowManager;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class AuthenticateWindow extends javax.swing.JDialog implements ViewConfigurable {

    /**
     * Creates new form AuthenticateWindow
     */
    public AuthenticateWindow() {
        setResizable(false);
        initComponents();

        setLocationRelativeTo(null);
        changeVisibility(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        secretCodeTextField = new javax.swing.JTextField();
        authenticateButton = new javax.swing.JButton();
        loadingLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/healthsystem/physician/Bundle"); // NOI18N
        setTitle(bundle.getString("AuthenticateWindow.title")); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        emailLabel.setText(bundle.getString("AuthenticateWindow.emailLabel.text")); // NOI18N
        jPanel1.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        secretCodeTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        secretCodeTextField.setText(bundle.getString("AuthenticateWindow.secretCodeTextField.text")); // NOI18N
        jPanel1.add(secretCodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 324, 34));

        authenticateButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        authenticateButton.setText(bundle.getString("AuthenticateWindow.authenticateButton.text")); // NOI18N
        authenticateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authenticateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(authenticateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 326, 36));

        loadingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loading_patient.gif"))); // NOI18N
        loadingLabel.setText(bundle.getString("AuthenticateWindow.loadingLabel.text")); // NOI18N
        jPanel1.add(loadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void authenticateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authenticateButtonActionPerformed

        changeVisibility(false);

        ExecutorService executor = Executors.newSingleThreadExecutor();
        executor.execute(() -> {
            String idUser = userDAO.getUserBySecretCode(secretCodeTextField.getText());

            System.out.println(idUser + " ------");
            if (!idUser.isEmpty()) {
                PatientModel patient = patientDAO.getPatient(idUser);
                if (patient != null) {
                    PatientPanel patientPanel = new PatientPanel();
                    patientPanel.setPatientModel(patient);
                    WindowManager.changePanel(patientPanel, physicianPanel);
                    dispose();
                }
                else{
                     setVisible(false);
                     JOptionPane.showMessageDialog(null, i18nLogin.getString("LoginScreen.userNotFound"));
                     dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, i18nLogin.getString("LoginScreen.notFound"));
                changeVisibility(true);

            }
        });
        executor.shutdown();


    }//GEN-LAST:event_authenticateButtonActionPerformed
    private java.util.ResourceBundle i18nLogin = java.util.ResourceBundle.getBundle("com/healthsystem/Bundle"); // NOI18N
    private PatientDAO patientDAO = new PatientDAO();
    private UserDAO userDAO = new UserDAO();
    private PhysicianPanel physicianPanel;

    public void setPhysicianPanel(PhysicianPanel physicianPanel) {
        this.physicianPanel = physicianPanel;
    }

    private void changeVisibility(boolean status) {
        emailLabel.setVisible(status);
        secretCodeTextField.setVisible(status);
        authenticateButton.setVisible(status);
        loadingLabel.setVisible(!status);
        jPanel1.revalidate();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton authenticateButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loadingLabel;
    private javax.swing.JTextField secretCodeTextField;
    // End of variables declaration//GEN-END:variables
}
