/*
 * Direitos reservados a Ramon Lacava Gutierrez Gonçales
 * ramonrune@gmail.com
 */
package com.healthsystem.physician;

import com.healthsystem.home.HomeScreen;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import jssc.SerialPort;
import jssc.SerialPortException;
import jssc.SerialPortList;

/**
 *
 * @author Usuario
 */
public class NFCReaderPanel extends javax.swing.JPanel {

    private java.util.ResourceBundle i18n = java.util.ResourceBundle.getBundle("com/healthsystem/physician/Bundle"); // NOI18N
    protected static boolean cont = true;
    public NFCReaderPanel() {
        initComponents();

        NFCReader.nfcReaderPanel = NFCReaderPanel.this;
        //nfcReader = new NFCReader();
        if (!NFCReader.setupOk()) {
            ExecutorService executor = Executors.newSingleThreadExecutor();
            executor.execute(() -> {

                while (cont) {

                    ExecutorService executor11 = Executors.newSingleThreadExecutor();
                    executor11.execute(() -> {
                        if (NFCReader.setupOk()) {

                            statusOk();
                            executor11.shutdown();
                            

                        } else {
                            statusNotOk();

                        }
                    });

                    try {

                        TimeUnit.MILLISECONDS.sleep(1000);

                    } catch (InterruptedException ex) {
                        Logger.getLogger(NFCReaderPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }

            });
        } else {
            statusOk();
        }

    }
    
   

    private void statusOk() {
        errorImageLabel.setVisible(false);
        imageLabel.setVisible(true);

        messageLabel.setText(i18n.getString("NFCReaderPanel.message.insert"));
        messageLabel.updateUI();
        imageLabel.updateUI();
        errorImageLabel.updateUI();
    }

    private void statusNotOk() {
        errorImageLabel.setVisible(true);
        errorImageLabel.updateUI();
        imageLabel.setVisible(false);
        imageLabel.updateUI();
        messageLabel.setText(i18n.getString("NFCReaderPanel.messageLabel.text"));
        messageLabel.updateUI();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        errorImageLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel("", SwingConstants.CENTER);

        setBackground(new java.awt.Color(255, 255, 255));

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nfc_loading.gif"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/healthsystem/physician/Bundle"); // NOI18N
        imageLabel.setText(bundle.getString("NFCReaderPanel.imageLabel.text")); // NOI18N
        imageLabel.setPreferredSize(null);

        errorImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usb_help.gif"))); // NOI18N
        errorImageLabel.setText(bundle.getString("NFCReaderPanel.errorImageLabel.text")); // NOI18N
        errorImageLabel.setMaximumSize(null);
        errorImageLabel.setMinimumSize(null);
        errorImageLabel.setPreferredSize(null);

        messageLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageLabel.setText(bundle.getString("NFCReaderPanel.messageLabel.text")); // NOI18N
        messageLabel.setMaximumSize(null);
        messageLabel.setMinimumSize(null);
        messageLabel.setPreferredSize(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(errorImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
            .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(errorImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE))
                    .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorImageLabel;
    public static javax.swing.JLabel imageLabel;
    public static javax.swing.JLabel messageLabel;
    // End of variables declaration//GEN-END:variables

}
